name: geiger_localstorage
description: A local storage for the GEIGER project providing an internationalized and event driven data storage.
version: 0.5.0
#homepage: https://github.com/cyber-geiger/toolbox-storage
repository: https://github.com/cyber-geiger/toolbox-storage
documentation: https://github.com/cyber-geiger/toolbox-storage/wiki




environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  uuid: ^3.0.4
  sqlite3: ^1.2.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
